### ISSUE TITLE
Multiple issues with IP literal parsing

### ISSUE THREAD

**Issue by yescallop** [lo48576/iri-string#17]
I found several issues with IP literal parsing in `iri-string` by fuzzing [`fluent-uri`](https://github.com/yescallop/fluent-uri-rs) against this crate. Here's a list of them, all of which can be reproduced by `<&RiReferenceStr<UriSpec>>::try_from` (abbreviated `try_from` hereafters).

- `try_from("//[::1]").unwrap().authority_components().unwrap().host()` gives `[:` instead of `[::1]`.
    It seems that a part of the host after the last `:` (inclusive) is truncated.
- `try_from("//[::1:]")` succeeds, which shouldn't happen because `::1:` is not a valid IPv6 address.
- According to RFC 3986, both the version and address of an IPvFuture literal are not empty. However, `try_from("//[v.]")` succeeds.
- The "v" of an IPvFuture is case-insensitive (see RFC3986), but `try_from("//[VF.A]")` fails.

**Comment by lo48576** [comment]
Thank you for reporting!
I published the fixes as [v0.5.1](https://crates.io/crates/iri-string/0.5.1) just now.

**Comment by yescallop** [comment]
Nice! But it seems that you forgot to fix the third issue?
> According to RFC 3986, both the version and address of an IPvFuture literal are not empty. However, try_from("//[v.]") succeeds.

**Comment by lo48576** [comment]
Thanks again! I've overlooked that...
Released v0.5.2.
