### ISSUE TITLE
Function to check if uri is normal

### ISSUE THREAD

**Issue by damooo** [lo48576/iri-string#18]
@lo48576 , thanks a lot for crate.

It would be helpful, if there is a function that can check if uri is normalized, with out allocation.

**Comment by lo48576** [comment]
[`RiAbsoluteStr::is_normalized`](https://docs.rs/iri-string/latest/iri_string/types/struct.RiAbsoluteStr.html#method.is_normalized) and [`RiStr::is_normalized`](https://docs.rs/iri-string/latest/iri_string/types/struct.RiStr.html#method.is_normalized) is implemented and released as v0.5.3.
