### ISSUE TITLE
Feature request: Support rfc6570 uri templates

### ISSUE THREAD

**Issue by damooo** [lo48576/iri-string#33]
[RFC 6570](https://www.rfc-editor.org/rfc/rfc6570) defines a syntax for uri templates. So that one can declaratively compute uri from variables instead of complex building.

It would be great addition to `iri_string`.

**Comment by lo48576** [comment]
Already implemented as [`template` module](https://docs.rs/iri-string/latest/iri_string/template/index.html).
Feel free to update and reopen this ticket if you have additional request.

**Comment by damooo** [comment]
Thanks and sorry. Should have checked docs properly.

**Comment by lo48576** [comment]
Never mind. Happens to everyone.
