### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by davidpdrsn** [lo48576/iri-string#4]
Hey! Any chance you would do a release? I'm using iri-string in [tower-http](https://crates.io/crates/tower-http) and getting two versions of nom pulled in. I see nom has been updated on the develop branch.

**Comment by lo48576** [comment]
Thank you for reporting!
Just now I published [0.4.0](https://crates.io/crates/iri-string/0.4.0).
All dependencies are up-to-date.

**Comment by davidpdrsn** [comment]
Thanks!
